FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "Docker_AspNetCore_MVC_Condominio.Web\Docker_AspNetCore_MVC_Condominio.Web.csproj"
RUN dotnet publish "Docker_AspNetCore_MVC_Condominio.Web\Docker_AspNetCore_MVC_Condominio.Web.csproj" -c Release -o /app/publish
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Docker_AspNetCore_MVC_Condominio.Web.dll"]