SELECT * FROM Condominio_mvc.dbo.AspNetUsers
SELECT * FROM Condominio_mvc.dbo.AspNetRoles
SELECT * FROM Condominio_mvc.dbo.AspNetUserRoles
SELECT * FROM Condominio_mvc.dbo.Empresa
SELECT * FROM Condominio_mvc.dbo.Imovel
SELECT * FROM Condominio_mvc.dbo.Morador
SELECT * FROM Condominio_mvc.dbo.Visitante
SELECT * FROM Condominio_mvc.dbo.Prestador
SELECT * FROM Condominio_mvc.dbo.EncomendasRecebidas
SELECT * FROM Condominio_mvc.dbo.EncomendasEntregues